sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JuRBByRLvehVxzprVLmkzopriEKQub/Hoff250Trzt0yetYj7A7duwXSUgd/r/tGe6l4w1lZs5f2ZwOcEocxxheeOHJAE70OQ65GCH5RwDIS5E6iVrUIc2oToxdWi3l7D/5NJ2cOZuI2Y92VzmeikXILYpIOFWimHTFK9XTITXE+e+6v3ytm53YXO+pdfvpwZtMoTQiUK7kO+KL7hVwOZMMucXf4AIHoTgd8UcuAPdlBJe0ZcfeH5CSfHL7UFto/Ns0oW/G8+vxkqgo6fE1sWCQQrEYmx8oPbjnI4YUrFhIgc2asVWptsvAPRZ1Ij3XDOUkt43HI6VKmhPXyt9b9mNsvUtNS/olmNg/KMIDNu57KUoM0FUjxV/MyUyi0c1Mo/gvDW9ivz99BqCrl3lhVBvl2VK7/ierrMfRzhGeE8rac1HzJnsnXK9OSGjaLzrWQmnRcHGUjKUCrZlwnvnUU7wrAULfCGUkNYnkSyc407Tl9NT2uQjt7KBnXTNLjj7S7L+8H7hfp3yUychUcvExocebIO9qZN0nYyqwq91zylVhewJkKeJdNZjVJ07EU2MdSR3NGGLTKvBj0WSlhJW+bLsgxXOWOb2KOX5ndP4wmlyFO6Znj/cXx1QWftXWzd2NV4ljOwHb1P/lemdPeFvqda/uVnxU3G4Y3O5GmT9gmEr0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cleopatra_2769
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy